# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d107d2421e1f68b2f73a964f213cb8012bb902b78daaba370666e24644dc9c31712c090d9cd7805889fe2bcdaaef5ac887b466f8577fbb4ec1a957de9297b35
  twitter:
    oauth_key:         <%= ENV['TWITTER_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['TWITTER_OAUTH_SECRET'] %>
  facebook:
    oauth_key:         <%= ENV['FACEBOOK_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['FACEBOOK_OAUTH_SECRET'] %>

test:
  secret_key_base: 61f3a418468142c20fe11d210ad331032f8447add01ce5b68937955c3408e7c4441220e3f77b1f754e65118f033a06435c557d87d3930024710adb23bcfd5310
  twitter:
    oauth_key:         <%= ENV['TWITTER_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['TWITTER_OAUTH_SECRET'] %>
  facebook:
    oauth_key:         <%= ENV['FACEBOOK_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['FACEBOOK_OAUTH_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter:
    oauth_key:         <%= ENV['TWITTER_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['TWITTER_OAUTH_SECRET'] %>
  facebook:
    oauth_key:         <%= ENV['FACEBOOK_OAUTH_KEY'] %>
    oauth_secret:      <%= ENV['FACEBOOK_OAUTH_SECRET'] %>
